from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.utils import safe_filename


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a config profile for a new Excel financial model.")
    parser.add_argument("--profile", required=True, help="Profile name, e.g. project_a")
    parser.add_argument("--draft-map", help="Path to draft_model_map.yaml generated by analyze_workbook.py")
    parser.add_argument("--template", default="config/model_map.yaml", help="Template map if --draft-map is omitted")
    parser.add_argument("--force", action="store_true", help="Overwrite existing profile")
    args = parser.parse_args()

    profile = safe_filename(args.profile)
    profile_dir = ROOT / "config" / "profiles" / profile
    if profile_dir.exists() and not args.force:
        raise FileExistsError(f"Profile already exists: {profile_dir}. Use --force to overwrite.")
    profile_dir.mkdir(parents=True, exist_ok=True)

    source = Path(args.draft_map) if args.draft_map else Path(args.template)
    if not source.is_absolute():
        source = ROOT / source
    if not source.exists():
        raise FileNotFoundError(source)

    shutil.copy2(source, profile_dir / "model_map.yaml")
    readme = profile_dir / "README.md"
    readme.write_text(
        f"# Profile: {profile}\n\n"
        "This profile was generated for one Excel workbook structure.\n\n"
        "Before using it, manually verify every input/output cell in `model_map.yaml`.\n\n"
        "Run validation:\n\n"
        f"```powershell\npython scripts/validate_profile.py --profile {profile} --excel \"models/your_model.xlsx\"\n```\n",
        encoding="utf-8",
    )
    print(f"Created profile: {profile_dir}")
    print(f"Edit and verify: {profile_dir / 'model_map.yaml'}")


if __name__ == "__main__":
    main()
